Lionel Andrés Messi Cuccittini:
  preferred_name: Lionel Messi
  aliases:
  - L. Messi
  - Lionel Messi
Cristiano Ronaldo dos Santos Aveiro:
  preferred_name: Cristiano Ronaldo
  aliases:
  - C. Ronaldo
  - Cristiano Ronaldo
Neymar da Silva Santos Junior:
  preferred_name: Neymar
  aliases:
  - Neymar Jr
  - Neymar
Kylian Mbappé Lottin:
  preferred_name: Kylian Mbappé
  aliases:
  - K. Mbappé
  - Kylian Mbappé
